language: ruby
dist: stretch
sudo: false
cache: bundler
rvm:
  - 2.6.2
addons:
  apt:
    update: true
env:
  - TRAVIS_CI=1
before_install:
  - "gem install bundler"
  - "sudo apt-get -y install vim-gtk3"
before_script:
  - "export DISPLAY=:99.0"
  - "vim --version"
script: "xvfb-run bundle exec rspec spec"
